CREATE TABLE USER(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
CONSTRAINT USE_PK PRIMARY KEY (ID));

CREATE TABLE CATEGORIES(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL,
CONSTRAINT CAT_PK PRIMARY KEY (ID));

CREATE TABLE CATEGORIES_COMPLAINT(
ID INT NOT NULL AUTO_INCREMENT,
CAT_ID INT NOT NULL,
COT_ID INT NOT NULL,
CONSTRAINT CC_PK PRIMARY KEY (ID),
CONSTRAINT CC_CAT_PK FOREIGN KEY (CAT_ID) REFERENCES CATEGORIES (ID),
CONSTRAINT CC_COT_FK FOREIGN KEY (COT_ID) REFERENCES COMPLAINT (ID));

CREATE TABLE COMPLAINT(
ID INT NOT NULL AUTO_INCREMENT,
COMMENT VARCHAR(300) NOT NULL,
CLAIM_DATE DATE NOT NULL,
TITLE VARCHAR(45) NOT NULL,
HOUR TIME NOT NULL,
LONGITUDE VARCHAR(100) NOT NULL,
LATITUDE VARCHAR(100) NOT NULL,
USE_ID INT NOT NULL,
CC_ID INT NOT NULL,
CONSTRAINT COT_PK PRIMARY KEY (ID),
CONSTRAINT COT_USE_FK FOREIGN KEY (USE_ID) REFERENCES USER (ID),
CONSTRAINT COT_CC_FK FOREIGN KEY (CC_ID) REFERENCES CATEGORIES_COMPLAINT (ID));

CREATE TABLE REACTION(
USE_ID INT NOT NULL,
COT_ID INT NOT NULL,
LIKE_DISLIKE INT NULL,
CONSTRAINT REA_USE_FK FOREIGN KEY (USE_ID) REFERENCES USER (ID),
CONSTRAINT REA_COT_FK FOREIGN KEY (COT_ID) REFERENCES COMPLAINT (ID));

CREATE TABLE COMMENT(
ID INT NOT NULL AUTO_INCREMENT,
COMMENT_ENGAGE VARCHAR(2500) NULL,
USE_ID INT NOT NULL,
COT_ID INT NOT NULL, 
CONSTRAINT COE_PK PRIMARY KEY (ID),
CONSTRAINT COE_USE_FK FOREIGN KEY (USE_ID) REFERENCES USER (ID),
CONSTRAINT COE_COT_FK FOREIGN KEY (COT_ID) REFERENCES COMPLAINT (ID));

CREATE TABLE USER_PROFILE(
ID INT NOT NULL AUTO_INCREMENT,
CPF INT NOT NULL,
ADRESS VARCHAR(100) NOT NULL,
CELL_PHONE INT NOT NULL,
BIRTH_DATE VARCHAR(45) NOT NULL,
USE_ID INT NOT NULL,
CONSTRAINT USP_PK PRIMARY KEY (ID),
CONSTRAINT USP_USE_FK FOREIGN KEY (USE_ID) REFERENCES USER (ID));

CREATE TABLE COMPANY_PROFILE(
ID INT NOT NULL AUTO_INCREMENT,
TYPE INT NOT NULL,
CNPJ VARCHAR(45) NOT NULL,
NAME_FANTASY VARCHAR(45) NOT NULL,
USE_ID INT NOT NULL,
CONSTRAINT COM_PK PRIMARY KEY (ID),
CONSTRAINT COM_USE_FK FOREIGN KEY (USE_ID) REFERENCES USER (ID));